---
title: "DATA 605 HW 1"
author: "Marley Myrianthopoulos"
date: "`r Sys.Date()`"
output: html_document
---

Part 1: Please note, my first and last initial are the same ("M") so I have elected to use my middle initial ("L") instead of my last initial.
```{r}

x=c(rep(-3,500), seq(-3,-2,length.out=500), seq(-2,-1,length.out=500), rep(-1,500), rep(1,500), seq(1,3,length.out=500))

y=c(seq(-3,3,length.out=500), seq(3,0,length.out=500), seq(0,3,length.out=500), seq(3,-3,length.out=500), seq(3,-3,length.out=500), rep(-3,500))

z=rbind(x,y)

plot(y~x, xlim=c(-10,10), ylim=c(-10,10))

```

```{r}

m <- diag(1,2,2) #Identity matrix in 2 dimensions

m1 <- matrix(c(1,0,0.5,1), nrow = 2, ncol = 2)

z1 <- m1 %*% z

x1 <- z1[1,]
y1 <- z1[2,]

plot(y1~x1, xlim=c(-1,20), ylim=c(-1,20))

```

```{r, fig.width=20,fig.height=20}

for(i in 0:20) {
  m2 <- matrix(c(1,0,0.025*i,1), nrow = 2, ncol = 2)
  z2 <- m2 %*% z
  x2 <- z2[1,]
  y2 <- z2[2,]

plot(y2~x2, xlim=c(-10,10), ylim=c(-10,10))
}

for(i in 1:20) {
  m2 <- matrix(c(1,0,0.5-0.025*i,1), nrow = 2, ncol = 2)
  z2 <- m2 %*% z
  x2 <- z2[1,]
  y2 <- z2[2,]

plot(y2~x2, xlim=c(-10,10), ylim=c(-10,10))
}

for(i in 1:20) {
  m2 <- matrix(c(1+0.05*i,0,0,1+0.05*i), nrow = 2, ncol = 2)
  z2 <- m2 %*% z
  x2 <- z2[1,]
  y2 <- z2[2,]

plot(y2~x2, xlim=c(-10,10), ylim=c(-10,10))
}

for(i in 1:20) {
  m2 <- matrix(c(2-0.05*i,0,0,2-0.05*i), nrow = 2, ncol = 2)
  z2 <- m2 %*% z
  x2 <- z2[1,]
  y2 <- z2[2,]

plot(y2~x2, xlim=c(-10,10), ylim=c(-10,10))
}

for(i in 1:20) {
  d = (18 * i)*(pi / 180)
  m2 <- matrix(c(cos(d),sin(d),-sin(d),cos(d)), nrow = 2, ncol = 2)
  z2 <- m2 %*% z
  x2 <- z2[1,]
  y2 <- z2[2,]
  
plot(y2~x2, xlim=c(-10,10), ylim=c(-10,10))
}

for(i in 1:20) {
  d = -1 * (18 * i)*(pi / 180)
  m2 <- matrix(c(cos(d),sin(d),-sin(d),cos(d)), nrow = 2, ncol = 2)
  z2 <- m2 %*% z
  x2 <- z2[1,]
  y2 <- z2[2,]
  
plot(y2~x2, xlim=c(-10,10), ylim=c(-10,10))
}

```

```{r}

m2 <- matrix(c(2,0,0,2), nrow = 2, ncol = 2)

z2 <- m2 %*% z

x2 <- z2[1,]
y2 <- z2[2,]

plot(y2~x2, xlim=c(-1,20), ylim=c(-1,20))

```

```{r}

for(i in 1:50) {
  m20 <- matrix(c(1+0.02*i,0,0,1+0.02*i), nrow = 2, ncol = 2)
  z20 <- m20 %*% z
  x20 <- z20[1,]
  y20 <- z20[2,]

plot(y20~x20, xlim=c(-1,20), ylim=c(-1,20))
}

```